# Generated by Django 3.1.3 on 2021-02-09 04:41

from django.db import migrations, models
import django.db.models.deletion
import stock.models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='InstituteName',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Inst_name', models.CharField(max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='item_software',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('software_name', models.CharField(max_length=100)),
                ('brand_name', models.CharField(max_length=100)),
                ('license', models.CharField(choices=[('Opensource', 'Opensource'), ('License', 'License'), ('freeware', 'freeware')], max_length=100)),
                ('license_doc', models.FileField(blank=True, upload_to='license_doc/', validators=[stock.models.validate_file_size])),
            ],
        ),
        migrations.CreateModel(
            name='ItemName',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('item_name', models.CharField(max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='RoomType',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('room_type', models.CharField(max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='ItemModel',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('model_name', models.CharField(max_length=100)),
                ('item_name', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='stock.itemname')),
            ],
        ),
        migrations.CreateModel(
            name='ItemDist',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('item_sl', models.CharField(max_length=100)),
                ('item_configuration', models.CharField(max_length=100, verbose_name='Items Specifications')),
                ('dept', models.CharField(max_length=100, verbose_name='Department')),
                ('block', models.CharField(max_length=100)),
                ('room', models.CharField(max_length=100, verbose_name='Room No')),
                ('item_qty', models.IntegerField()),
                ('act', models.IntegerField(default=1)),
                ('remark', models.CharField(blank=True, max_length=100)),
                ('inst', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='stock.institutename', verbose_name='Institute Name')),
                ('item_model', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='stock.itemmodel')),
                ('item_name', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='stock.itemname')),
                ('room_type', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='stock.roomtype')),
            ],
            options={
                'verbose_name_plural': 'Item Distribution',
            },
        ),
    ]
