# Generated by Django 3.1.4 on 2021-02-22 15:44

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('stock', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='itemdist',
            options={'verbose_name': 'Item Distribution'},
        ),
    ]
