# Generated by Django 3.1.3 on 2021-02-25 07:10

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('stock', '0004_itemdist_acblock'),
    ]

    operations = [
        migrations.AlterField(
            model_name='itemdist',
            name='acblock',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='stock.ac_block', verbose_name='Academic Block'),
        ),
    ]
