# Generated by Django 3.1.4 on 2021-03-03 14:03

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('stock', '0005_auto_20210225_1240'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='itemdist',
            name='block',
        ),
        migrations.RemoveField(
            model_name='itemdist',
            name='dept',
        ),
        migrations.RemoveField(
            model_name='itemdist',
            name='remark',
        ),
    ]
