# Generated by Django 3.1.3 on 2021-03-12 04:27

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('stock', '0007_itemdist_user'),
    ]

    operations = [
        migrations.DeleteModel(
            name='item_software',
        ),
    ]
