# Generated by Django 3.2.5 on 2021-07-18 12:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('stock', '0008_delete_item_software'),
    ]

    operations = [
        migrations.AddField(
            model_name='itemdist',
            name='updated_at',
            field=models.DateTimeField(auto_now=True),
        ),
        migrations.AlterField(
            model_name='itemdist',
            name='act',
            field=models.IntegerField(default=0, editable=False),
        ),
    ]
