# Generated by Django 3.1.7 on 2021-07-19 11:17

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('stock', '0009_auto_20210718_1730'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='institutename',
            options={'ordering': ['Inst_name']},
        ),
        migrations.AlterModelOptions(
            name='itemname',
            options={'ordering': ['item_name']},
        ),
    ]
