# Generated by Django 3.2.5 on 2021-07-20 12:23

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('stock', '0010_auto_20210719_1647'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='itemdist',
            name='item_sl',
        ),
    ]
