# Generated by Django 3.2.5 on 2021-07-20 12:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('stock', '0011_remove_itemdist_item_sl'),
    ]

    operations = [
        migrations.AddField(
            model_name='itemdist',
            name='purchase_date',
            field=models.DateField(blank=True, null=True),
        ),
    ]
