# Generated by Django 2.2.10 on 2021-08-27 10:42

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('stock', '0012_itemdist_purchase_date'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='ac_block',
            options={'ordering': ['name']},
        ),
        migrations.CreateModel(
            name='ItemPurchase',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('item_purchase_date', models.DateField(blank=True, null=True)),
                ('item_sl', models.CharField(max_length=100)),
                ('item_configuration', models.CharField(max_length=100, verbose_name='Items Specifications')),
                ('item_vendor', models.CharField(max_length=100, verbose_name='Vendor Name')),
                ('item_invoice', models.CharField(max_length=100, verbose_name='Invoice No')),
                ('item_price', models.CharField(max_length=100, verbose_name='Price')),
                ('item_qty', models.IntegerField()),
                ('item_bill_scan', models.FileField(upload_to='media/invoice/%d/%m/%y')),
                ('item_model', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='stock.ItemModel')),
                ('item_name', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='stock.ItemName')),
            ],
            options={
                'verbose_name': 'Item Purchase',
            },
        ),
    ]
