# Generated by Django 2.2.10 on 2021-08-27 11:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('stock', '0013_auto_20210827_1612'),
    ]

    operations = [
        migrations.AlterField(
            model_name='itempurchase',
            name='item_bill_scan',
            field=models.ImageField(upload_to='invoice/'),
        ),
    ]
