# Generated by Django 2.2.10 on 2021-08-28 06:08

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('stock', '0015_auto_20210828_1136'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='itempurchase',
            name='item_bill_scan',
        ),
    ]
