# Generated by Django 3.2.8 on 2021-12-02 02:50

from django.db import migrations, models
import stock.models


class Migration(migrations.Migration):

    dependencies = [
        ('stock', '0016_remove_itempurchase_item_bill_scan'),
    ]

    operations = [
        migrations.AddField(
            model_name='itemname',
            name='item_image',
            field=models.ImageField(blank=True, help_text='Maximum file size allowed is 6KB', upload_to='item-pic', validators=[stock.models.validate_image]),
        ),
    ]
