# Generated by Django 3.2.8 on 2021-12-02 05:29

from django.db import migrations, models
import stock.models


class Migration(migrations.Migration):

    dependencies = [
        ('stock', '0017_itemname_item_image'),
    ]

    operations = [
        migrations.AddField(
            model_name='itempurchase',
            name='item_invoice_file',
            field=models.FileField(blank=True, help_text='Maximum file size allowed is 2KB', upload_to='invoice/', validators=[stock.models.validate_file_size], verbose_name='Invoice Doc'),
        ),
        migrations.AlterField(
            model_name='itemname',
            name='item_image',
            field=models.ImageField(blank=True, help_text='Maximum file size allowed is 100KB', upload_to='item-pic', validators=[stock.models.validate_image]),
        ),
    ]
