# Generated by Django 4.0 on 2021-12-08 09:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('stock', '0018_auto_20211202_1059'),
    ]

    operations = [
        migrations.AlterField(
            model_name='itempurchase',
            name='item_invoice_file',
            field=models.FileField(blank=True, help_text='Maximum file size allowed is 100KB', upload_to='invoice/'),
        ),
    ]
