# Generated by Django 4.0 on 2021-12-14 15:23

from django.db import migrations, models
import stock.models


class Migration(migrations.Migration):

    dependencies = [
        ('stock', '0019_alter_itempurchase_item_invoice_file'),
    ]

    operations = [
        migrations.AlterField(
            model_name='itempurchase',
            name='item_invoice_file',
            field=models.FileField(blank=True, help_text='Maximum file size allowed is 500KB', upload_to='invoice', validators=[stock.models.validate_file_size]),
        ),
    ]
