# Generated by Django 4.0.1 on 2022-01-22 03:01

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('stock', '0021_alter_itempurchase_item_invoice_file'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='roomtype',
            options={'ordering': ['room_type']},
        ),
    ]
