# Generated by Django 4.0 on 2022-02-01 14:42

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('stock', '0022_alter_roomtype_options'),
    ]

    operations = [
        migrations.CreateModel(
            name='ItemScrap',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('item_scarp_date', models.DateField(blank=True, null=True)),
                ('item_configuration', models.CharField(max_length=100, verbose_name='Items Specifications')),
                ('purchase_date', models.DateField(blank=True, null=True)),
                ('scrap_type', models.CharField(choices=[('SCRAP', 'SCRAP'), ('DONATE', 'DONATE')], default='SCRAP', max_length=10, verbose_name='Scrap Type')),
                ('item_qty', models.IntegerField()),
                ('item_vendor', models.CharField(max_length=100, verbose_name='Vendor Name')),
                ('item_model', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='stock.itemmodel')),
                ('item_name', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='stock.itemname')),
            ],
            options={
                'verbose_name': 'Item Scarp',
            },
        ),
    ]
