# Generated by Django 4.0.1 on 2022-01-06 04:05

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('stock', '0021_alter_itempurchase_item_invoice_file'),
        ('userprofile', '0002_alter_profile_avatar'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='profile',
            name='city',
        ),
        migrations.RemoveField(
            model_name='profile',
            name='zip',
        ),
        migrations.AddField(
            model_name='profile',
            name='inst',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='stock.institutename', verbose_name='Institute Name'),
        ),
    ]
