# Generated by Django 4.0 on 2022-01-06 11:08

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('userprofile', '0003_remove_profile_city_remove_profile_zip_profile_inst'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='profile',
            name='number',
        ),
    ]
