# Generated by Django 4.0.1 on 2022-01-22 03:01

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('stock', '0022_alter_roomtype_options'),
        ('userprofile', '0004_remove_profile_number'),
    ]

    operations = [
        migrations.AlterField(
            model_name='profile',
            name='inst',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='stock.institutename', verbose_name='Institute Name'),
        ),
    ]
